// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend_shopping_dotnet.Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20240808090724_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Vegetable",
                            Name = "Carrot",
                            Price = 1.99
                        },
                        new
                        {
                            Id = 2,
                            Category = "Vegetable",
                            Name = "Broccoli",
                            Price = 1.29
                        },
                        new
                        {
                            Id = 3,
                            Category = "Vegetable",
                            Name = "Lettuce",
                            Price = 0.79000000000000004
                        },
                        new
                        {
                            Id = 4,
                            Category = "Vegetable",
                            Name = "Tomato",
                            Price = 0.89000000000000001
                        },
                        new
                        {
                            Id = 5,
                            Category = "Vegetable",
                            Name = "Cucumber",
                            Price = 0.68999999999999995
                        },
                        new
                        {
                            Id = 6,
                            Category = "Vegetable",
                            Name = "Pepper",
                            Price = 1.1899999999999999
                        },
                        new
                        {
                            Id = 7,
                            Category = "Meat",
                            Name = "Chicken Breast",
                            Price = 5.9900000000000002
                        },
                        new
                        {
                            Id = 8,
                            Category = "Meat",
                            Name = "Beef Steak",
                            Price = 12.99
                        },
                        new
                        {
                            Id = 9,
                            Category = "Meat",
                            Name = "Pork Chop",
                            Price = 8.4900000000000002
                        },
                        new
                        {
                            Id = 10,
                            Category = "Meat",
                            Name = "Lamb Leg",
                            Price = 15.99
                        },
                        new
                        {
                            Id = 11,
                            Category = "Meat",
                            Name = "Turkey Breast",
                            Price = 6.9900000000000002
                        },
                        new
                        {
                            Id = 12,
                            Category = "Meat",
                            Name = "Ground Beef",
                            Price = 4.9900000000000002
                        },
                        new
                        {
                            Id = 13,
                            Category = "Electronic Devices",
                            Name = "Smartphone",
                            Price = 299.99000000000001
                        },
                        new
                        {
                            Id = 14,
                            Category = "Electronic Devices",
                            Name = "Laptop",
                            Price = 999.99000000000001
                        },
                        new
                        {
                            Id = 15,
                            Category = "Electronic Devices",
                            Name = "Tablet",
                            Price = 199.99000000000001
                        },
                        new
                        {
                            Id = 16,
                            Category = "Electronic Devices",
                            Name = "Smartwatch",
                            Price = 149.99000000000001
                        },
                        new
                        {
                            Id = 17,
                            Category = "Electronic Devices",
                            Name = "Headphones",
                            Price = 79.989999999999995
                        },
                        new
                        {
                            Id = 18,
                            Category = "Electronic Devices",
                            Name = "Bluetooth Speaker",
                            Price = 49.990000000000002
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
